sales_landing:
  source_schema:
  source_table:
  target_schema: bronze_layer
  target_table: sales_landing
customers_landing:
  source_schema:
  source_table:
  target_schema: bronze_layer
  target_table: customers_landing